name: Upload QuantumOX Binaries

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  Artifacts:
    name: ${{ matrix.config.name }} ${{ matrix.binaries }}
    runs-on: ubuntu-latest
    env:
      EXT: ${{ matrix.config.ext }}
      NAME: ${{ matrix.config.simple_name }}
      BINARY: ${{ matrix.binaries }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifact from compilation
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.config.simple_name }} ${{ matrix.binaries }}
          path: ${{ matrix.config.simple_name }} ${{ matrix.binaries }}

      - name: Prepare package
        run: |
          mkdir QuantumOX
          mv "${{ matrix.config.simple_name }} ${{ matrix.binaries }}" QuantumOX/

      - name: Copy docs and scripts
        run: |
          cp README.md QuantumOX/
          cp CONTRIBUTING.md QuantumOX/
          cp LICENSE QuantumOX/
          cp CHANGELOG.md QuantumOX/ || true

      - name: Create tar (Linux/macOS)
        if: ${{ !startsWith(matrix.config.os, 'windows') }}
        run: |
          chmod +x ./QuantumOX/${{ matrix.config.simple_name }} ${{ matrix.binaries }}
          tar -cvf QuantumOX-${{ matrix.config.simple_name }}-${{ matrix.binaries }}.tar QuantumOX

      - name: Create zip (Windows)
        if: ${{ startsWith(matrix.config.os, 'windows') }}
        run: |
          zip -r QuantumOX-${{ matrix.config.simple_name }}-${{ matrix.binaries }}.zip QuantumOX

      - name: Release on GitHub
        if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            QuantumOX-${{ matrix.config.simple_name }}-${{ matrix.binaries }}.${{ matrix.config.archive_ext }}
          token: ${{ secrets.token }}

      - name: Get last commit sha
        id: last_commit
        run: echo "COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV

      - name: Get commit date
        id: commit_date
        run: echo "COMMIT_DATE=$(git show -s --date=format:'%Y%m%d' --format=%cd HEAD)" >> $GITHUB_ENV

      - name: Prerelease (dev builds)
        if: github.ref_name == 'master'
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          name: QuantumOX-dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          tag_name: quantumox-dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          prerelease: true
          files: |
            QuantumOX-${{ matrix.config.simple_name }}-${{ matrix.binaries }}.${{ matrix.config.archive_ext }}
          token: ${{ secrets.token }}
